### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by kupiakos** [zappala/bene#6]
Given that Python 2 will be deprecated soon ([as early as 2020](https://pythonclock.org/)), education should generally be avoiding it. The benefits that Python 3 bring are great, one of the largest being Unicode strings by default. I'd like to use Python 3 exclusively in this class if possible.

I'll look into the difficulty of porting the CS 460 stub code to be compatible with Python 2.7 and 3. Adding the `six` library as a requirement may be needed.

**Comment by zappala** [comment]
I was actually thinking of porting bene to Python 3 this week and requiring 3 this semester. Do you have time to contribute?

**Comment by zappala** [comment]
I am fine with leaving 2 behind.

**Comment by kupiakos** [comment]
That's great to hear! 👍 Yes, I should have time to contribute. I was planning on starting tonight. Was also thinking of PEP8 reformatting the code if possible as well. Any thoughts?

**Comment by zappala** [comment]
Sounds good to me. This will help me a lot to get this done quickly before I make an assignment with it. Thanks! That will let me focus on improving the labs and documentation.

I think ditching the six library and just supporting Python 3 is fine with me, because I'd like to keep the requirements as minimal as possible.

**Comment by kupiakos** [comment]
I've made a [pull request](https://github.com/zappala/bene/pull/7) for the PEP 8 changes, if you'd prefer to pull that in first so we are working with the same Python 2 code. My `python3` branch will be branching off of this.

**Comment by zappala** [comment]
Done, great work, thanks.

**Comment by kupiakos** [comment]
It looks like the pull request is still open?
